### ISSUE TITLE
Mask dataset

### ISSUE THREAD

**Issue by trungpham2606** [lkeab/BCNet#28]
Dear @lkeab 
According to this picture in your paper:
![image](https://user-images.githubusercontent.com/35657426/120912447-55765580-c6b9-11eb-8347-c671a635d79c.png)
So, every objects will have full mask no matter they are occluder or occludee ?

**Comment by lkeab** [comment]
It depends on amodal or modal segmentation. For amodal, yes. For modal, we only using the visible mask for the occluders and occludee(target object) within the same RoI. 

During training, for each instance i, we first get its bounding box Bi, and then using the GT annotation file to find all neighboring objects within bounding box and overlapping with the Bi, and then crop/group their mask annotations inside the box Bi as occluders. Thus, we treat the object itself as occludee and the other overlapping objects inside Bi as the occluders. You can also refer to the python file related to process.sh for more details.

During the test time, since our network has bilayer structure, the first image layer will detects the occluders while the second layer will predict the occludee.

**Comment by trungpham2606** [comment]
@lkeab 
I think the occluder and occludee are used for describing the object in front and back respectively ? why dont you define an instance whether is occluder or occludee before training ?
Because according to your idea about occluder and occludee, an instance can be both occluder and occludee, I think it will affect the Bi layer, makes it confusing ?

**Comment by lkeab** [comment]
Hi, thanks for the suggestion. I dit it for several reasons: 1) no depth information contains in annotations, if you need it manually define front-back positions, the workload would be huge (the instance amount in coco is huge). 2) also in some situations, there will be self-occlusion of no definitive front-back order 3) Thus, as an approximate, for each RoI, we treat its target object as occludee and the neighboring overlapping objects in RoI for occluders.

**Comment by trqminh** [comment]
Hi @lkeab ,
Thank you for your consideration.
Regarding the question "every object will have a full mask no matter they are occluder or occludee?", it is yes for the amodal task.

I would like to ask about the COCO-OCC, is that split has full masks for every object from the beginning? If not, how you can conduct the mask for the ocludees?
